---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-cleanup-config
  namespace: confluent
type: Opaque
stringData:
  # Format: YYYY-MM-DD
  # Kafka and KRaftController CRDs will be deleted after this date
  cleanup-date: "2026-06-30"

  # Set to "true" to test without actually deleting
  dry-run: "false"
